services:
  mongo-catalog:
    image: mongo:7
    container_name: mongo-catalog
    ports:
      - "27017:27017"
    volumes:
      - mongo_catalog_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand({ ping: 1 }).ok\" | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATA_MONGODB_URI: mongodb://mongo-catalog:27017/catalogdb
    depends_on:
      mongo-catalog:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo_catalog_data: